name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check commit message
        id: commit
        run: |
          commit_hash=$(git log --grep="chore(release):" --format=format:%H -n 1)
          commit_message=$(git log --format=%B -n 3 ${{ github.event.after }})
          if [[ "$commit_message" == *"chore(release):"* ]]; then
            echo "::set-output name=trigger::true"
            echo "::set-output name=hash::${commit_hash}"
          fi
      - name: Run job based on commit message
        if: steps.commit.outputs.trigger == 'true'
        run: |
          echo "Running job because commit message started with 'chore(release):'"
          git tag v$(cat VERSION.txt) ${{ steps.commit.outputs.hash }}
          git push origin $(cat VERSION.txt)
