name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check commit message
        id: commit
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.event.after }})
          if [[ "$commit_message" == "chore(release):"* ]]; then
            echo "::set-output name=trigger::true"
          fi
      - name: Run job based on commit message
        if: steps.commit.outputs.trigger == 'true'
        run: |
          echo "Running job because commit message started with 'chore(release):'"
          git tag v$(cat VERSION.txt)
          git push origin v$(cat VERSION.txt)
