name: Custom Release Workflow

on:
  push:
    branches:
      - main

jobs:
  check_commit:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check commit message and maybe tag
        id: commit
        run: |
          commit_hash=$(git log --grep="chore(release):" --format=format:%H -n 1)
          if [[ -n "$commit_hash" ]]; then
            git tag v$(cat VERSION.txt) $commit_hash
            git push origin v$(cat VERSION.txt)
          fi
